### ISSUE TITLE
Incorrect Opening of Code Snippet in Markdown

### ISSUE THREAD

**Issue by noel-lopez** [Alan-TheGentleman/gentleman-programming-book#6]
There is an unnecessary "```markdown" line in the documentation that causes the following text to be incorrectly styled as a code snippet on the book webpage. 

https://github.com/Alan-TheGentleman/gentleman-programming-book/blob/404779d2ee8ad5fde8824896e6e7c44300bb177c/src/data/book/en/Chapter04_GoLang.mdx?plain=1#L276-L283

This issue is visible [here](https://the-amazing-gentleman-programming-book.vercel.app/es/book/Chapter04_GoLang#punteros).

**Comment by Alan-TheGentleman** [comment]
meged !!!
